# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './designer/gobang_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 1000)
        MainWindow.setMinimumSize(QtCore.QSize(1300, 1000))
        MainWindow.setMaximumSize(QtCore.QSize(1300, 1000))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.chessboard = QtWidgets.QWidget(self.centralwidget)
        self.chessboard.setGeometry(QtCore.QRect(0, 0, 1000, 1000))
        self.chessboard.setStyleSheet("border-image: url(:/bg/image/chessboard.png);")
        self.chessboard.setObjectName("chessboard")
        self.whites = QtWidgets.QWidget(self.centralwidget)
        self.whites.setGeometry(QtCore.QRect(1030, 50, 220, 220))
        self.whites.setStyleSheet("background-image: url(:/bg/image/whites-removebg-preview.png);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.whites.setObjectName("whites")
        self.black = QtWidgets.QWidget(self.centralwidget)
        self.black.setGeometry(QtCore.QRect(1030, 720, 220, 220))
        self.black.setStyleSheet("border-image: url(:/bg/image/blacks-removebg-preview.png);")
        self.black.setObjectName("black")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(998, -1, 301, 1000))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-image: url(:/bg/image/bg.png);")
        self.widget.setObjectName("widget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(1015, 331, 261, 121))
        self.textBrowser.setStyleSheet("background-color: rgba(255, 255, 255, 150);")
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1060, 340, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1030, 370, 111, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1030, 400, 161, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(1010, 500, 271, 141))
        self.textBrowser_2.setStyleSheet("background-color: rgba(255, 255, 255, 150);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1080, 565, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(1060, 555, 43, 43))
        self.widget_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"background-image: url(:/bg/image/avator2.png);")
        self.widget_2.setObjectName("widget_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1050, 530, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1040, 600, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(240, 239, 521, 191))
        font = QtGui.QFont()
        font.setPointSize(90)
        self.result_label.setFont(font)
        self.result_label.setText("")
        self.result_label.setObjectName("result_label")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1030, 430, 161, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.widget.raise_()
        self.chessboard.raise_()
        self.whites.raise_()
        self.black.raise_()
        self.textBrowser.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.textBrowser_2.raise_()
        self.label_4.raise_()
        self.widget_2.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.result_label.raise_()
        self.label_7.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:6pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10.8pt;\"><br /></p></body></html>"))
        self.label.setText(_translate("MainWindow", "五子棋（人机博弈）"))
        self.label_2.setText(_translate("MainWindow", "步数：0"))
        self.label_3.setText(_translate("MainWindow", "时间：00:00"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:6pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10.8pt;\"><br /></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "     作者： sgsx"))
        self.label_5.setText(_translate("MainWindow", "版本 1.1.0 - 2021年11月"))
        self.label_6.setText(_translate("MainWindow", "联系方式：1287997451@qq.com"))
        self.label_7.setText(_translate("MainWindow", "轮到你了！"))
import gobang_qrc_rc
